# Generated by Django 2.2.1 on 2020-08-29 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('Fullname', models.CharField(max_length=255)),
                ('Nickname', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Birthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Description', models.TextField()),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
                ('Attachments', models.FileField(blank=True, upload_to='')),
                ('EventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.User')),
            ],
        ),
    ]
