# Generated by Django 3.1 on 2020-09-03 15:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250, verbose_name='عنوان')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eventname', models.CharField(max_length=500)),
                ('Description', models.TextField()),
                ('CreateDatetime', models.DateTimeField(default=datetime.datetime(2020, 9, 3, 19, 40, 52, 612156))),
                ('Attachments', models.FileField(blank=True, upload_to='')),
                ('event_datetime', models.DateTimeField(blank=True, null=True)),
                ('optional', models.BooleanField(blank=True, null=True, verbose_name='اختیاری است؟')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.category')),
            ],
        ),
    ]
