# Generated by Django 2.2.1 on 2020-08-29 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='EventID',
            new_name='EventOwner',
        ),
    ]
