# Generated by Django 3.1 on 2020-09-03 15:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20200903_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Attachments',
            field=models.FileField(blank=True, upload_to='', verbose_name='پیوست'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='CreateDatetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 3, 19, 44, 52, 22178), verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='Description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='Eventname',
            field=models.CharField(max_length=500, verbose_name='نام رخداد'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.category', verbose_name='دسته'),
        ),
    ]
