# Generated by Django 3.1 on 2020-09-04 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20200903_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='last_time_edited',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='آخرین تغییرات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='Attachments',
            field=models.FileField(blank=True, upload_to='media', verbose_name='پیوست'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='CreateDatetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
